### ISSUE TITLE
Additional work required for SvelteKit

### ISSUE THREAD

**Issue by revick** [metaplex-foundation/js-examples#16]
Manually updated the 'arbundles' package imports from noble-ed25519 to @noble/ed25519 to get it to work with SvelteKit. Rest of the vite instructions still hold.

**Comment by revick** [comment]
Fix incoming: https://github.com/Bundlr-Network/arbundles/issues/51#issuecomment-1196350770

**Comment by revick** [comment]
Fixed in the latest arbundles version 0.6.20

**Comment by lorisleiva** [comment]
Thank you! 🍺
