### ISSUE TITLE
Is there a missing `.run` in the code?

### ISSUE THREAD

**Issue by mikemaccana** [metaplex-foundation/js-examples#19]
At https://github.com/metaplex-foundation/js-examples/blob/main/getting-started-expressjs/index.cjs#L38 0 shouldn't there be a `run()`?

**Comment by lorisleiva** [comment]
Hi 👋 

Yes, there should! I've not had the time to update these examples with the latest SDK version yet I'm afraid.

Thanks for raising this.

**Comment by zaxozhu** [comment]
@lorisleiva Hi! I think this issue has been resolved. `run()` is there
